### ISSUE TITLE
Consider removing collapsable DIVs

### ISSUE THREAD

**Issue by johnpapa** [microsoft/codespaces-teaching-template-js#10]
For the following reasons:

1. I'm not sure if these are Accessible. 
2. It may not be obvious to those with vision that these can be clicked on 
3. Expanding them won't add complexity

**Comment by saragibby** [comment]
Great points! I originally included collapsible divs as way to reduce the text overwhelm on initial view of readme and was something I see used in GitHub Skills. However, as we have continued to refine the text it has gotten simplified and removing any need to collapse sections. Thanks for the suggestion!
