### ISSUE TITLE
Add details on how to use this a remote devcontainer within VScode 

### ISSUE THREAD

**Issue by leestott** [microsoft/codespaces-teaching-template-js#14]
Sara 

Would recommend adding to the instructions how to use the repo as dev container image for students and educators when they don't have connectivity to codespaces.

See https://microsoft.sharepoint.com/teams/OneComplianceLearningHub/SitePages/Activating-Inclusion.aspx as an example of the text

**Comment by saragibby** [comment]
Thanks @leestott for pointing out! I'm adding a link to https://github.com/microsoft/vscode-remote-try-node in the resources section now. But going to leave this open as I feel like there may still be a need to include the instructions, and it wouldn't be that much additional text to add to the readme.
