### ISSUE TITLE
Edit readme after removing 'npm run start' from automatic execution

### ISSUE THREAD

**Issue by juliamuiruri4** [microsoft/codespaces-teaching-template-js#19]
Hi, 
After merging Burke's PR, https://github.com/microsoft/codespaces-teaching-template-js/pull/3, a minor update on the readme instructions is necessary as npm run start is no longer being executed automatically.

![image](https://user-images.githubusercontent.com/40116776/194055609-9ffd84ba-b5e4-49e1-94a8-f43ebd712d04.png)

Might be worth mentioning to the reader that they would need to manually run the command after `npm install` completes

**Comment by juliamuiruri4** [comment]
![image](https://user-images.githubusercontent.com/40116776/194059712-7d8fe5e1-ef21-4314-97bb-f00b56595bf4.png)

Here too.

**Comment by saragibby** [comment]
Thanks for calling out @juliamuiruri4! I updated the readme to include change this instruction to call out that the user will need to run `npm run start` separately in the terminal. Let me know if you think it will help to expalin any more in that section.
