### ISSUE TITLE
Clarity of Intention 

### ISSUE THREAD

**Issue by johnpapa** [microsoft/codespaces-teaching-template-js#4]
From the readme description, it appears that the intention is to use this repo for lessons

> With this JS Codespace template you can immediately create a lesson that provides a consistent starting point for all your students. Allow you as the educator to focus on the web development content you are teaching, and let us handle the environment setup for you.

The naming of the repo implies its for teaching , but would it be clearer if it was for teachers? (if that is the intention). Also, it's not quite clear to me what we mean by "template". Will the educator know? 

After walking through this, it feels like this is a sample or example app that can be used to demonstrate Codespaces. Do we have a sense from the educators if "template" resonates with them? Template to me, feels like it is something I take and modify. Not something I use like a "grab and go" example. 

While it may seem pedantic, I feel naming is important so we it resonates with the customer. 

What do you think?

**Comment by saragibby** [comment]
Thanks for bringing up this point @johnpapa! It forced me to go through the readme again to bring focus back to the educator audience. There are more opportunities to provide educators with specific instances on how to use this with our curricula, but I'd like to do that through some Educator blog posts to start. Bringing revisions to this content as we get feedback and see how educators are utilizing it.
