### ISSUE TITLE
Should we focus more on Web and less on React?

### ISSUE THREAD

**Issue by johnpapa** [microsoft/codespaces-teaching-template-js#5]
React is a great choice here as it has wide appeal. But as you point out, no matter what Web framework we choose, someone will wonder how to use it with their framework ... or even if this is something they can use at all.

I was thinking ... what if we focus on Web (more high level) in the text rather than that it uses React? It's perfectly fine to mention React , and we should. I hypothesize that if we focus on the "Web" aspects (even HTML/JS/CSS) more-so in the text, perhaps more folks will continue exploring and using it (first impressions) than if someone who doesnt use React sees it everywhere in the text and thinks "well, this is not for me".

I'll make a PR for this and see what you think

**Comment by johnpapa** [comment]
see #8

**Comment by saragibby** [comment]
Great suggestion @johnpapa! I got your changes merged in and took another pass through the readme. Will continue to refine to be sure we keep to a web development audience and not focus in on React.
