### ISSUE TITLE
Regarding the topic of switching frameworks

### ISSUE THREAD

**Issue by johnpapa** [microsoft/codespaces-teaching-template-js#7]
In the section **2. Change to a different frontend Web framework* the first section talks about Node.js. This is the first time (I think) that we mention Node. Do we need to? Is it clear why we're doing this? Will the educators be clear? 

Immediately after this we show how to switch from React to another framework by removing files. Will they know what files to remove?  It might take some further discussion to figure out the best way to do this ... or perhaps for now, we don't show this?

**Comment by saragibby** [comment]
I appreciate you mentioning this @johnpapa! It is a great point, and while going through the material again to ensure an educator focus, it occurred to me that I missed noting the included linter. I have now replaced the step to change the framework to how to adjust the linter rules. This felt to be a better fit for educators as it would allow them to set code rules and quality for students' projects. As always, feedback and thoughts on this change are appreciated!

**Comment by saragibby** [comment]
@johnpapa closing this issue out since I have this now replaced with section with a linter step, and in prep to get this repo transferred. Look forward to continuing to iterate on this as we get feedback. 😊
