### ISSUE TITLE
Add images and video to Readme

### ISSUE THREAD

**Issue by johnpapa** [microsoft/codespaces-teaching-template-js#9]
You asked: 

> What image and/or video content can we include ?

I think this is a great idea. Even something simple like a picture of the Codespaces environment running with the React app. perhaps even open in Codewing?

Something that allows the to visualize would be great.

**Comment by saragibby** [comment]
Thanks @johnpapa! Images and gif added to project. Will continue to review and watch for feedback on other areas in readme to include graphics for better user experience.
